### ISSUE TITLE
Aktueller Branch

### ISSUE THREAD

**Issue by zuphilip** [gemeinsamerverbuendeindex/gvi#4]
Welches ist der aktuelle branch?

https://github.com/gemeinsamerverbuendeindex/gvi/branches

Der master branch ist auf Stand von Februar aber beispielsweise der branch cleanup.ant hat seitdem 303 neue commits bekommen.

**Comment by Hirnfiedler** [comment]
Hallo Phillip,
ja, 'master' ist in diesem Projekt nur eine Referenz, vergleichbar mit einem Tag 'Aktuelles Produktivsystem'.
In den fast gleichen Zweigen 'cleanup.ant' und 'cleanup.ant2' findet die Weiterentwicklung statt, die den GVI deutlich verbessern und bald in Produktion übernommen werden.
_(Ja das ist nicht 'Best Praxis', aber zur Zeit unsere funktionierende Arbeitsbasis)_

**Comment by zuphilip** [comment]
Okay, bin gespannt auf die neue Version!

Man könnte "master = Stand Produktivsystem; andere branchs = aktuelle Weiterentwicklung" in der README erwähnen.
